##################################################################
# DSMR-API-logger koppeling neem op in de configuration.yaml     #
##################################################################
# mqtt: pas de state-topic aan indien nodig                      #
# rest: pas de hostname aan indien nodig bij resource            #
##################################################################

sensor:
  - platform: mqtt
    name: "Gebruik"
    state_topic: "DSMR-API/power_delivered" 
    unit_of_measurement: "kWh"
    value_template: '{{ value_json.power_delivered[0].value | round(3) }}'

  - platform: mqtt
    name: "Laatste Update mqtt"
    state_topic: "DSMR-API/timestamp" 
#   value_template: '{{ value_json.timestamp[0].value }}'
    value_template: >
      {{      value_json.timestamp[0].value[4:6] + "-" + 
              value_json.timestamp[0].value[2:4] + "-" + 
         "20"+value_json.timestamp[0].value[0:2] + "   " + 
              value_json.timestamp[0].value[6:8] + ":" + 
              value_json.timestamp[0].value[8:10] + ":" + 
              value_json.timestamp[0].value[10:13] }}

  - platform: mqtt
    name: "Gebruik l1"
    state_topic: "DSMR-PRD/power_delivered_l1"
    unit_of_measurement: 'Watt'
    value_template: "{{ (value_json.power_delivered_l1[0].value | float * 1000.0) | round(1) }}"

  - platform: mqtt
    name: "Gebruik l2"
    state_topic: "DSMR-PRD/power_delivered_l2"
    unit_of_measurement: 'Watt'
    value_template: "{{ (value_json.power_delivered_l2[0].value | float * 1000.0) | round(1) }}"

  - platform: mqtt
    name: "Gebruik l3"
    state_topic: "DSMR-PRD/power_delivered_l3"
    unit_of_measurement: 'Watt'
    value_template: "{{ (value_json.power_delivered_l3[0].value | float * 1000.0) | round(1) }}"


  - platform: rest
    name: "Levering"
    resource: http://dsmr-api.local/api/v2/sm/fields/power_returned
    unit_of_measurement: "kWh"
    value_template: '{{ value_json.power_returned.value | round(3) }}'

  - platform: rest
    name: "Laatste Update restAPI"
    resource: http://dsmr-api.local/api/v2/sm/fields/timestamp
#   value_template: '{{ value_json.fields[0].value }}'
    value_template: >
      {{      value_json.timestamp.value[4:6] + "-" + 
              value_json.timestamp.value[2:4] + "-" + 
         "20"+value_json.timestamp.value[0:2] + "   " + 
              value_json.timestamp.value[6:8] + ":" + 
              value_json.timestamp.value[8:10] + ":" + 
              value_json.timestamp.value[10:13] }}

  - platform: rest
    name: "Levering l1"
    resource: http://dsmr-api.local/api/v2/sm/fields/power_returned_l1
    unit_of_measurement: "Watt"
    value_template: '{{ (value_json.power_returned_l1.value | float * 1000.0) | round(1) }}'

  - platform: rest
    name: "Levering l2"
    resource: http://dsmr-api.local/api/v2/sm/fields/power_returned_l2
    unit_of_measurement: 'Watt'
    value_template: '{{ (value_json.power_returned_l2.value | float * 1000.0) | round(1) }}'

  - platform: rest
    name: "Levering l3"
    resource: http://dsmr-api.local/api/v2/sm/fields/power_returned_l3
    unit_of_measurement: 'Watt'
    value_template: '{{ (value_json.power_returned_l3.value | float * 1000.0) | round(1) }}'