### sensor: ###
### DSMR-API ###

- platform: mqtt
  name: "LWT"
  state_topic: "DSMR-API/LWT"
  availability:
    - topic: "DSMR-API/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "DSMR Last Update"
  state_topic: "DSMR-API/timestamp"
  unit_of_measurement: ""
  value_template: "{{ strptime(value_json.timestamp[0].value, '%y%m%d%H%M%SW') }}"

- platform: mqtt
  name: "Energy Delivered T1"
  state_topic: "DSMR-API/energy_delivered_tariff1" 
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.energy_delivered_tariff1[0].value | round(3) }}"
  object_id: energy_delivered_tariff1

- platform: mqtt
  name: "Energy Delivered T2"
  state_topic: "DSMR-API/energy_delivered_tariff2" 
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.energy_delivered_tariff2[0].value | round(3) }}"
  object_id: energy_delivered_tariff2

- platform: mqtt
  name: "Energy Returned T1"
  state_topic: "DSMR-API/energy_returned_tariff1" 
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.energy_returned_tariff1[0].value | round(3) }}"

- platform: mqtt
  name: "Energy Returned T2"
  state_topic: "DSMR-API/energy_returned_tariff2" 
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.energy_returned_tariff2[0].value | round(3) }}"

- platform: mqtt
  name: "Power Delivered"
  state_topic: "DSMR-API/power_delivered" 
  unit_of_measurement: "kW"
  value_template: "{{ value_json.power_delivered[0].value | round(3) }}"

- platform: mqtt
  name: "Power Returned"
  state_topic: "DSMR-API/power_returned"
  unit_of_measurement: "kW"
  value_template: "{{ value_json.power_returned[0].value | round(3) }}"

- platform: mqtt
  name: "Power Delivered l1"
  state_topic: "DSMR-API/power_delivered_l1" 
  unit_of_measurement: "Watt"
  value_template: "{{ value_json.power_delivered_l1[0].value | round(1) }}"

- platform: mqtt
  name: "Power Delivered l2"
  state_topic: "DSMR-API/power_delivered_l2" 
  unit_of_measurement: "Watt"
  value_template: "{{ value_json.power_delivered_l2[0].value | round(1) }}"

- platform: mqtt
  name: "Power Delivered l3"
  state_topic: "DSMR-API/power_delivered_l3" 
  unit_of_measurement: "Watt"
  value_template: "{{ value_json.power_delivered_l3[0].value | round(1) }}"

- platform: mqtt
  name: "Power Returned l1"
  state_topic: "DSMR-API/power_returned_l1"
  unit_of_measurement: "Watt"
  value_template: "{{ value_json.power_returned_l1[0].value | round(1) }}"

- platform: mqtt
  name: "Power Returned l2"
  state_topic: "DSMR-API/power_returned_l2"
  unit_of_measurement: "Watt"
  value_template: "{{ value_json.power_returned_l2[0].value | round(1) }}"

- platform: mqtt
  name: "Power Returned l3"
  state_topic: "DSMR-API/power_returned_l3"
  unit_of_measurement: "Watt"
  value_template: "{{ value_json.power_returned_l3[0].value | round(1) }}"

- platform: mqtt
  name: "Gas Delivered"
  state_topic: "DSMR-API/gas_delivered"
  unit_of_measurement: "m3"
  value_template: "{{ value_json.gas_delivered[0].value | round(2) }}"